[book]
authors = ["AddonScript Team", "Timo Ley"]
language = "en"
multilingual = false
src = "docs"
title = "AddonScript"

[build]
build-dir = "public"

[output.html]
git-repository-url = "https://git.tilera.org/AddonScript/addonscript-spec"
