[book]
authors = ["AddonScript Team", "Timo Ley"]
language = "en"
multilingual = false
src = "docs"
title = "AddonScript"

[output.html]
git-repository-url = "https://tilera.xyz/git/AddonScript/addonscript-spec"
